import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import Logo from "./components/Logo";
import { Button } from "@heroui/react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar
          brand={
            <>
              <Logo />
              <p className="font-bold">ACME</p>
            </>
          }
          items={[
            { label: "Features", href: "#features" },
            { label: "Dashboard", href: "#dashboard", isActive: true },
            { label: "Pricing", href: "#pricing" },
          ]}
          rightContent={
            <>
              <Link href="#login">Login</Link>
              <Button>Sign Up</Button>
            </>
          }
        />
        {children}
      </body>
    </html>
  );
}
